New_School_CRM-main/New_School_CRM-main/apps/students/urls.py
from django.urls import path
from . import views 
from .views import *


from .views import (
    DownloadCSVViewdownloadcsv,
    StudentBulkUploadView,
    StudentCreateView,
    StudentDeleteView,
    StudentDetailView,
    StudentListView,
    StudentUpdateView,
   
)

urlpatterns = [
    path("list", StudentListView.as_view(), name="student-list"),
    path("<int:pk>/", StudentDetailView.as_view(), name="student-detail"),
    path("create/", StudentCreateView.as_view(), name="student-create"),
    path("<int:pk>/update/", StudentUpdateView.as_view(), name="student-update"),
    path("delete/<int:pk>/", StudentDeleteView.as_view(), name="student-delete"),
    path("upload/", StudentBulkUploadView.as_view(), name="student-upload"),
    path("download-csv/", DownloadCSVViewdownloadcsv.as_view(), name="download-csv"),

    path('data/', views.studentdata, name='student-data'),
    path('report/', views.studentreport, name='student-report'),
    path('attendance/', views.studentattendance, name='student-attendance'),

    path('leaverequest/', views.student_leave_request, name='student-leave-request'),


    ##### new url for student reportcard

    path("reportcard/", views.student_report_card_view, name="student-report-card"),

    ##### attendance url
    path('student/attendance/', views.student_attendance_view, name='student-attendance-report'),

]

New_School_CRM-main/New_School_CRM-main/school_app/urls.py
# from django.conf import settings
# from django.conf.urls.static import static
# from django.urls import include, path

# urlpatterns = [
#     path("accounts/", include("django.contrib.auth.urls")),
#     path("", include("apps.corecode.urls")),
#     path("student/", include("apps.students.urls")),
#     path("staff/", include("apps.staffs.urls")),
#     path("finance/", include("apps.finance.urls")),
#     path("result/", include("apps.result.urls")),
# ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



# from django.conf import settings
# from django.conf.urls.static import static
# from django.urls import include, path
# from django.contrib.auth import views as auth_views
# from . import views

# urlpatterns = [
#     path("accounts/", include("django.contrib.auth.urls")),
#     path("", include("apps.corecode.urls")),
#     path("student/", include("apps.students.urls")),
#     path("staff/", include("apps.staffs.urls")),
#     path("finance/", include("apps.finance.urls")),
#     path("result/", include("apps.result.urls")),


#     # path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
#     # path('signup/', views.signup, name='signup'),
#     # path('logout/', auth_views.LogoutView.as_view(), name='logout'),
# ]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from django.contrib import admin  # Import the admin module
from django.contrib.auth import views as auth_views
from . import views  
from django.contrib import admin
from django.urls import path, include
# from .views import profile_view

urlpatterns = [
    path("admin/", admin.site.urls),  # Add this line for the admin panel
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("apps.corecode.urls")),
    path("student/", include("apps.students.urls")),
    path("staff/", include("apps.staffs.urls")),
    path("principal/", include("apps.principal.urls")),
    path("finance/", include("apps.finance.urls")),
    path("result/", include("apps.result.urls")),
    path('index/', views.index, name='index'),  # This points to the index view
    path('password_change/', views.change_password, name='password_change'),
    path('password_change/done/', views.index, name='password_change_done'),


    #  path('profile/', profile_view, name='profile'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

New_School_CRM-main/New_School_CRM-main/apps/students/models.py
from django.core.validators import RegexValidator
from django.db import models
from django.urls import reverse
from django.utils import timezone

from apps.corecode.models import StudentClass


class Student(models.Model):
    STATUS_CHOICES = [("active", "Active"), ("inactive", "Inactive")]

    GENDER_CHOICES = [("male", "Male"), ("female", "Female")]

    current_status = models.CharField(
        max_length=10, choices=STATUS_CHOICES, default="active"
    )
    registration_number = models.CharField(max_length=200, unique=True)
    surname = models.CharField(max_length=200)
    firstname = models.CharField(max_length=200)
    other_name = models.CharField(max_length=200, blank=True)
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES, default="male")
    date_of_birth = models.DateField(default=timezone.now)
    current_class = models.ForeignKey(
        StudentClass, on_delete=models.SET_NULL, blank=True, null=True
    )
    date_of_admission = models.DateField(default=timezone.now)

    mobile_num_regex = RegexValidator(
        regex="^[0-9]{10,15}$", message="Entered mobile number isn't in a right format!"
    )
    parent_mobile_number = models.CharField(
        validators=[mobile_num_regex], max_length=13, blank=True
    )

    address = models.TextField(blank=True)
    others = models.TextField(blank=True)
    passport = models.ImageField(blank=True, upload_to="students/passports/")

    class Meta:
        ordering = ["surname", "firstname", "other_name"]

    def __str__(self):
        return f"{self.surname} {self.firstname} {self.other_name} ({self.registration_number})"

    def get_absolute_url(self):
        return reverse("student-detail", kwargs={"pk": self.pk})


class StudentBulkUpload(models.Model):
    date_uploaded = models.DateTimeField(auto_now=True)
    csv_file = models.FileField(upload_to="students/bulkupload/")




############## new model for student details

# students/models.py

from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone 

class LeaveRequeststudent(models.Model):
    student = models.ForeignKey(User, on_delete=models.CASCADE)
    standard = models.CharField(max_length=50)
    reason = models.TextField()
    date_applied = models.DateTimeField(auto_now_add=True)
    
    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('approved', 'Approved'),
        ('rejected', 'Rejected'),
    ]
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='pending')

    def __str__(self):
        return f"{self.student.username} - {self.status}"


########### new models for student report card

# from django.db import models
# from django.contrib.auth.models import User
# from apps.corecode.models import StudentClass

# class StuReportCard(models.Model):
#     student = models.ForeignKey(User, on_delete=models.CASCADE)
#     standard = models.ForeignKey(StudentClass, on_delete=models.SET_NULL, null=True, blank=True)
    
#     tamil = models.PositiveIntegerField()
#     english = models.PositiveIntegerField()
#     maths = models.PositiveIntegerField()
#     science = models.PositiveIntegerField()
#     social = models.PositiveIntegerField()

#     status = models.CharField(max_length=10, choices=[("pass", "Pass"), ("fail", "Fail")])
#     comments = models.TextField(blank=True)
#     parent_signature = models.BooleanField(default=False)

#     created_at = models.DateTimeField(auto_now_add=True)

#     def __str__(self):
#         return f"{self.student.username} - {self.standard}"



#### model for updated 

from django.db import models
from django.contrib.auth.models import User
from apps.corecode.models import StudentClass, AcademicSession
from ckeditor.fields import RichTextField

class StuReportCard(models.Model):
    student = models.ForeignKey(User, on_delete=models.CASCADE)
    standard = models.ForeignKey(StudentClass, on_delete=models.SET_NULL, null=True, blank=True)
    section = models.CharField(max_length=10, blank=True)
    academic_session = models.ForeignKey(AcademicSession, on_delete=models.SET_NULL, null=True, blank=True)

    father_name = models.CharField(max_length=100, blank=True)
    mother_name = models.CharField(max_length=100, blank=True)
    address = RichTextField(blank=True)
    admission_number = models.CharField(max_length=30, blank=True)
    roll_number = models.CharField(max_length=30, blank=True)
    date_of_birth = models.DateField(null=True, blank=True)

    tamil = models.PositiveIntegerField()
    english = models.PositiveIntegerField()
    maths = models.PositiveIntegerField()
    science = models.PositiveIntegerField()
    social = models.PositiveIntegerField()

    overall_total = models.PositiveIntegerField(default=0)
    overall_percentage = models.FloatField(default=0.0)
    overall_grade = models.CharField(max_length=5, default="", blank=True)

    status = models.CharField(max_length=10, choices=[("pass", "Pass"), ("fail", "Fail")])
    term = models.CharField(max_length=10, choices=[("Term I", "Term I"), ("Term II", "Term II")], default="")
    comments = RichTextField(blank=True)

    date = models.CharField(max_length=50, blank=True)
    signature_class_teacher = models.CharField(max_length=100, blank=True)
    signature_principal = models.CharField(max_length=100, blank=True)
    parent_signature = models.BooleanField(default=False)

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.student.username} - {self.standard} - {self.term}"


###### Attendance report card model


from django.db import models
from django.contrib.auth.models import User

ATTENDANCE_STATUS = (
    ('present', 'Present'),
    ('absent', 'Absent'),
    ('permission', 'Permission'),
)

DAYS = (
    ('mon', 'Monday'),
    ('tue', 'Tuesday'),
    ('wed', 'Wednesday'),
    ('thu', 'Thursday'),
    ('fri', 'Friday'),
)

class AttendanceRecord(models.Model):
    student = models.ForeignKey(User, on_delete=models.CASCADE)
    month = models.CharField(max_length=20)
    date = models.DateField()
    day = models.CharField(max_length=10, choices=DAYS)
    status = models.CharField(max_length=15, choices=ATTENDANCE_STATUS)
    message = models.TextField(blank=True)
    signature = models.CharField(max_length=100, blank=True)

    class Meta:
        ordering = ['-date']

    def __str__(self):
        return f"{self.student.username} - {self.date} - {self.status}"

New_School_CRM-main/New_School_CRM-main/apps/students/views.py
import csv

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.forms import widgets
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView, View
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from apps.finance.models import Invoice

from .models import Student, StudentBulkUpload


# class StudentListView(LoginRequiredMixin, ListView):
#     model = Student
#     template_name = "students/student_list.html"

class StudentListView(LoginRequiredMixin, ListView):
    model = Student
    template_name = "students/student_list.html"
    context_object_name = 'students'

    def get_queryset(self):
        queryset = super().get_queryset()
        # print("Students in queryset:", queryset)  # Debugging line
        return queryset


class StudentDetailView(LoginRequiredMixin, DetailView):
    model = Student
    template_name = "students/student_detail.html"

    def get_context_data(self, **kwargs):
        context = super(StudentDetailView, self).get_context_data(**kwargs)
        context["payments"] = Invoice.objects.filter(student=self.object)
        return context


class StudentCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Student
    fields = "__all__"
    success_message = "New student successfully added."

    def get_form(self): 
        """add date picker in forms"""
        form = super(StudentCreateView, self).get_form()
        form.fields["date_of_birth"].widget = widgets.DateInput(attrs={"type": "date"})
        form.fields["address"].widget = widgets.Textarea(attrs={"rows": 2})
        form.fields["others"].widget = widgets.Textarea(attrs={"rows": 2})
        return form


class StudentUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Student
    fields = "__all__"
    success_message = "Record successfully updated."

    def get_form(self):
        """add date picker in forms"""
        form = super(StudentUpdateView, self).get_form()
        form.fields["date_of_birth"].widget = widgets.DateInput(attrs={"type": "date"})
        form.fields["date_of_admission"].widget = widgets.DateInput(
            attrs={"type": "date"}
        )
        form.fields["address"].widget = widgets.Textarea(attrs={"rows": 2})
        form.fields["others"].widget = widgets.Textarea(attrs={"rows": 2})
        # form.fields['passport'].widget = widgets.FileInput()
        return form


class StudentDeleteView(LoginRequiredMixin, DeleteView):
    model = Student
    success_url = reverse_lazy("student-list")


class StudentBulkUploadView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = StudentBulkUpload
    template_name = "students/students_upload.html"
    fields = ["csv_file"]
    success_url = "/student/list"
    success_message = "Successfully uploaded students"


class DownloadCSVViewdownloadcsv(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        response = HttpResponse(content_type="text/csv")
        response["Content-Disposition"] = 'attachment; filename="student_template.csv"'

        writer = csv.writer(response)
        writer.writerow(
            [
                "registration_number",
                "surname",
                "firstname1",
                "other_names1",
                "gender1",
                "parent_number1",
                "address1",
                "current_class",
            ]
        )

        return response


#######/////////// checking for redirecting stude_index.html page

# from django.contrib.auth.decorators import login_required
# from django.shortcuts import render
# from .decorators import role_required


# @login_required
# @role_required('student')
# def student_dashboard(request):
#     return render(request, 'templates/students/student_dashboard.html')

############### working good, ela pageku correct ah naviagate agum


from django.shortcuts import  render

def studentreport(request):
    # return render(request, 'corecode/student_dashboard.html')s
    return render(request, 'students/student_report.html')


# def studentattendance(request):
#     # return render(request, 'corecode/student_dashboard.html')s
#     return render(request, 'students/student_attendance.html')


######### old student_attendance function

from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
# from .models import LeaveRequeststudent

# @login_required
# def studentattendance(request):
#     student = request.user
#     leaves = LeaveRequeststudent.objects.filter(student=student)
#     return render(request, 'students/student_attendance.html', {'leaves': leaves})

from .models import LeaveRequeststudent
from .forms import LeaveRequeststudentForm

@login_required
def studentattendance(request):
    student = request.user
    leaves = LeaveRequeststudent.objects.filter(student=student)

    if request.method == "POST":
        form = LeaveRequeststudentForm(request.POST)
        if form.is_valid():
            leave = form.save(commit=False)
            leave.student = student
            leave.save()
            return redirect('student-attendance')
    else:
        form = LeaveRequeststudentForm()

    return render(request, 'students/student_attendance.html', {
        'leaves': leaves,
        'form': form
    })



# def studentdashboard(request):
#     return render (request, 'students/student_dashboard.html')


def studentdata(request):
    # return render (request, 'students/student_data.html')
    return render (request, 'students/student_leave_request.html')


# students/views.py

from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import LeaveRequeststudentForm
from .models import LeaveRequeststudent


@login_required
def student_leave_request(request):
    if request.method == 'POST':
        form = LeaveRequeststudentForm(request.POST)
        if form.is_valid():
            leave = form.save(commit=False)
            leave.student = request.user
            leave.save()
            return redirect('student-attendance')  # or show confirmation
    else:
        form = LeaveRequeststudentForm()
    
    return render(request, 'students/student_leave_request.html', {'form': form})



####### new models for student report card

from .models import StuReportCard
from django.contrib.auth.decorators import login_required

@login_required
def student_report_card_view(request):
    cards = StuReportCard.objects.filter(student=request.user)
    return render(request, 'students/student_report_card.html', {'cards': cards})



####### attendance record functions for student

# students/views.py

from .models import AttendanceRecord
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

@login_required
def student_attendance_view(request):
    records = AttendanceRecord.objects.filter(student=request.user)
    return render(request, 'students/student_attendance_report.html', {'records': records})

New_School_CRM-main/New_School_CRM-main/apps/students/templates/students/student_attendance.html
<style>
    table {
        border-collapse: collapse;
        width: 100%;
    }
    th, td {
        border: 1px solid black;
        padding: 10px;
        text-align: start;
    }
    thead {
        background-color: #FF7D7D;
    }
    /* NEW working colors */
    .pending {
        color: orange;
        font-weight: bold;
    }
    .approved {
        color: green;
        font-weight: bold;
    }
    .rejected {
        color: red;
        font-weight: bold;
    }
    .submit-btn button{
        background-color: #FF7D7D;
        border-color: transparent;
        color: white;
        border-radius: 3px;
    }
    tbody tr {
        font-size: 16px;
        background-color: #E3E3E3;
    }
    tbody tr:hover {
    background-color: #c8c7c7;
    cursor: pointer;
}
</style>


{% extends 'students/student_index.html' %}

{% block title %}
  Attendance / Leave Management
{% endblock title %}

{% block breadcrumb %}
  <h5>Attendance</h5>
{% endblock breadcrumb %}

{% block content %}
        <h4 class="text-center">Student's Leave Status</h4>

        <table>
            <thead>
                <tr>
                    <th>Student</th>
                    <th>Standard</th>
                    <th>Reason</th>
                    <th>Date Applied</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                {% for leave in leaves %}
                <tr>
                    <td>{{ leave.student.username }}</td>
                    <td>{{ leave.standard }}</td>
                    <td>{{ leave.reason }}</td>
                    <td>{{ leave.date_applied }}</td>
                    <td>
                        {% with leave.status|lower as status_lower %}
                            {% if status_lower == "pending" %}
                                <span class="pending">{{ leave.status }}</span>
                            {% elif status_lower == "approved" %}
                                <span class="approved">{{ leave.status }}</span>
                            {% elif status_lower == "rejected" %}
                                <span class="rejected">{{ leave.status }}</span>
                            {% else %}
                                {{ leave.status }}
                            {% endif %}
                        {% endwith %}
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="5">No leave requests submitted.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        
        

        <hr>

        <!-- Leave Request Form -->
        <h3>Add Leave Request</h3>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="submit-btn">
                <button type="submit">Submit Leave Request</button>
            </div>
        </form>

{% endblock content %}

New_School_CRM-main/New_School_CRM-main/apps/students/templates/students/student_attendance_report.html
<style>
    table {
        border-collapse: collapse;
        width: 100%;
    }
    th, td {
        border: 1px solid black;
        padding: 10px;
        text-align: start;
    }
    thead {
        background-color: #FF7D7D;
    }
    tbody tr {
        font-size: 16px;
        background-color: #E3E3E3;
    }
    tbody tr:hover {
    background-color: #c8c7c7;
    cursor: pointer;
}
</style>

{% extends 'students/student_index.html' %}

{% block content %}
<h4 class="text-center">Student Attenance</h4>
<table>
    <thead>
        <tr>
            <th>Date</th><th>Day</th><th>Status</th><th>Message</th><th>Signature</th>
        </tr>
    </thead>
    {% for record in records %}
    <tr>
        <td>{{ record.date }}</td>
        <td>{{ record.get_day_display }}</td>
        <td>{{ record.get_status_display }}</td>
        <td>{{ record.message }}</td>
        <td>{{ record.signature }}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

New_School_CRM-main/New_School_CRM-main/apps/students/templates/students/student_confirm_delete.html
{% extends 'base.html' %}


{% block title %}
{% endblock title %}


{% block content %}

<form action="" method="POST">
  {% csrf_token %}

  <div class="alert">
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <p>All contents attached to this student will be deleted</p>
  </div>

  <input type="submit" class="btn btn-primary" value="Confirm">

</form>


{% endblock content %}

New_School_CRM-main/New_School_CRM-main/apps/students/templates/students/student_dashboard.html
{# templates/students/student_dashboard.html #}
{% extends 'students/student_index.html' %}

{% block title %}
  Student Dashboard
{% endblock title %}

{% block breadcrumb %}
  Students
{% endblock breadcrumb %}

{% block content %}
  <h3>Welcome to the Student Dashboard</h3>
  <p>This is the dashboard page for students. You can view your activities, reports, etc.</p>
{% endblock content %}

New_School_CRM-main/New_School_CRM-main/apps/students/templates/students/student_data.html
{% extends 'students/student_index.html' %}

{% block title %}
  Student Dashboard
{% endblock title %}

{% block breadcrumb %}
  Students
{% endblock breadcrumb %}

{% block content %}
  <h3>Welcome to the Student Dashboard</h3>
  <p>This is the dashboard page for students. You can view your activities, reports, etc.</p>
{% endblock content %}

New_School_CRM-main/New_School_CRM-main/apps/students/templates/students/student_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content-header %}
<div class="card-header">
  <div class="card-tools">
    <a href="#" class="btn btn-tool">Print</a>
    <a href="{% url 'student-update' object.id %}" class="btn btn-tool">
      <i class="fas fa-edit"></i>
    </a>
    <a href="{% url 'student-delete' object.id %}" class="btn btn-tool">
      <i class="fas fa-times"></i>
    </a>
  </div>
</div>
{% endblock content-header %}

{% block content %}
    <div class="row mb-4">
      <div class="col-sm-4">
        <div class="row mb-2">

          {% if object.passport %}
            <img
              src="{{ object.passport.url }}"
              class="float-left rounded-circle mr-3" style="width: 120px; height: 120px;">
          {% else %}
            <img
              src="{% static 'dist/img/avatar.png' %}"
              class="float-left rounded-circle mr-3" style="width: 120px; height: 120px;">
          {% endif %}


          <div class="float-right">
            <h4>Surname:{{ object.surname }} </h4>
            <h4>FirstName:{{ object.firstname }} </h4>
            <h4>LastName:{{ object.other_name }} </h4>
            <h4>Reg-No:{{ object.registration_number }} </h4>
          </div>
        </div>
        <h5>Class:{{ object.current_class }} </h5>
        <h5>Gender: {{ object.get_gender_display }} | Status:{{ object.get_current_status_display }}</h5>

      </div>
      <div class="col-sm-8">
        <div>
          <div class="form-group border-bottom row">
            <label class="col">
              Date of Birth
            </label>
            <div class="col">
              {{ object.date_of_birth }}
            </div>
          </div>

          <div class="form-group border-bottom row">
            <label class="col">
              Parent Mobile Number
            </label>
            <div class="col">
              {{ object.parent_mobile_number}}
            </div>
          </div>

          <div class="form-group border-bottom row">
            <label class="col">
              Address
            </label>
            <div class="col">
              {{ object.address }}
            </div>
          </div>
          <div class="form-group border-bottom row">
            <label class="col">
              Comments
            </label>
            <div class="col">
              {{ object.others }}
            </div>
          </div>

        </div>

      </div>
    </div>

    <h4>Invoice/Payment History</h4>
    {% if payments %}
      <table class="table table-sm table-bordered table-hover">
        <thead class="thead-light">
          <tr>
            <th>For</th>
            <th>Amount Payable</th>
            <th>Amount Paid</th>
            <th>balance</th>
          </tr>
        </thead>
        <tbody>
          {% for payment in payments %}
            <tr class='clickable-row' data-href="{% url 'invoice-detail' payment.id %}">
              <td>{{payment.session}} - {{payment.term}} - {{ payment.class_for}}</td>
              <td>{{payment.total_amount_payable}}</td>
              <td>{{payment.total_amount_paid}}</td>
              <td>{{payment.balance}}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
        <p>There are no payment history for {{object}}</p>
    {% endif %}




{% endblock content %}

New_School_CRM-main/New_School_CRM-main/apps/students/templates/students/student_form.html
{% extends 'base.html' %}


{% block title %}

  {% if object %}
    Update {{ object }}
  {% else %}
    Add new student
  {% endif %}

{% endblock title %}


{% block content %}

<form action="" method="POST" enctype="multipart/form-data">
  {% csrf_token %}

  {% include 'corecode/form_snippet.html' %}

  {% if object %}
    <input type="submit" class="btn btn-primary" value="Update Record">
  {% else %}
    <input type="submit" class="btn btn-primary" value="Add new student">
  {% endif %}
</form>


{% endblock content %}

New_School_CRM-main/New_School_CRM-main/apps/students/templates/students/student_leave_request.html
{% extends 'students/student_index.html' %}
{% block content %}
<h2>Request Leave for student</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit Leave (student)</button>
</form>
{% endblock %}

New_School_CRM-main/New_School_CRM-main/apps/students/templates/students/student_list.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Students{% endblock title %}

{% block breadcrumb %}
<a class="btn btn-primary" href="{% url 'student-create' %}"><i class="fas fa-plus"></i> New student</a>
<!-- <a class="btn btn-primary" href="{% url 'student-upload' %}"><i class="fas fa-upload"></i> Upload students</a> -->
{% endblock breadcrumb %}


{% block content %}
  <div class="table-responsive">
    <table id="studenttable" class="table table-bordered table-hover" data-page-length='100'>
      <thead class="thead-light">
        <tr>
          <th>S/N</th>
          <th>Registration Number</th>
          <th>Fullname</th>
          <th>Current Class</th>
          <th>Gender</th>
          <th>Mobile Phone Number</th>
          <th>Status</th>
          <th>Address</th>
          <th>Passport</th>
        </tr>
      </thead>
      <tbody>
        {% for student in students %}
          <tr class='clickable-row' data-href="{% url 'student-detail' student.id %}">
            <td>{{ forloop.counter }}</td>
            <td>{{ student.registration_number }}</td>
            <td>{{ student.surname }} {{ student.firstname }} {{ student.other_name }}</td>
            <td>{{ student.current_class }}</td>
            <td>{{ student.get_gender_display }}</td>
            <td>{{ student.parent_mobile_number }}</td>
            <td>{{ student.get_current_status_display }}</td>
            <td>{{ student.address }}</td>
            <td>
              {% if student.passport %}
                <img src="{{ student.passport.url }}" alt="{{ student.fullname }}" style="width: 50px; height: auto;">
              {% else %}
                <img src="{% static 'dist/img/avatar.png' %}" alt="Default Avatar" style="width: 50px; height: auto;">
                <!-- <img src="{% static 'dist/img/avatar.png' %}" class="float-left rounded-circle mr-3" style="width: 120px; height: 120px;"> -->
              {% endif %}
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock content %}

{% block morejs %}
<script>
   $('#studenttable').DataTable({
    select: false
    });
</script>

{% endblock morejs %}

New_School_CRM-main/New_School_CRM-main/apps/students/templates/students/students_upload.html
{% extends 'base.html' %}


{% block title %}
  Upload Bulk Students from file
{% endblock title %}


{% block content %}

  <div class="col alert alert-info">
    <h5>Instruction</h5>
    <p>Please <a href="{% url 'download-csv' %}">download the CSV file attached here</a>. Fill in the sheet and upload the same file back to this page. DO NOT EDIT THE FIRST ROW</p>
  </div>

  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% include 'corecode/form_snippet.html' %}

    <input type="submit" class="btn btn-success" value="Submit">
  </form>

{% endblock content %}